#!/bin/bash

SERVERURL="https://changeme.live.dynatrace.com"
APITOKEN="CHANGEMECHANGEMECHANG"
APDEX_VERSION="1.0"

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

cd ${BASE}

docker run \
	--rm \
	-it \
	--name apdex \
	-p 8080:8080 \
	dynatrace/apdex:${APDEX_VERSION} \
	-serverurl "${SERVERURL}" -apitoken "${APITOKEN}"

